name: test

on:
  push:
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu-latest

    runs-on: ${{ matrix.os }}
    
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_HOST_AUTH_METHOD: trust
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: '^1.23.7'
          cache-dependency-path: ./go.sum
      - uses: actions/checkout@v4
      
      - name: Setup PostgreSQL
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client
          
      - name: Create test database
        run: |
          createdb -h localhost -U postgres pq_types
        env:
          PGPASSWORD: postgres
          
      - name: Build
        run: go build .
      - name: Test
        run: go test -v ./...
        env:
          PGPASSWORD: postgres
