name: test

on:
  push:
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: '^1.23.7'
          cache-dependency-path: ./go.sum
      - uses: actions/checkout@v4
      - name: Build
        run: go build .
      - name: Test
        run: go test -v ./...
